name: Deploy HTML to SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to SFTP
      env:
        SFTP_HOST: ${{ secrets.SFTP_HOST }}
        SFTP_PORT: ${{ secrets.SFTP_PORT }}
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
      run: |
        echo 'hello'
        sudo apt-get install sshpass
        sshpass -p "$SFTP_PASSWORD" scp -P 21 -r "./" "$SFTP_USERNAME@$SFTP_HOST:/"

